### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/checksum-verifier#4] opened 2016-06-13 11:24 UTC
If Akismet is deleted, the plugin still gives warnings about checksum problems:
https://wordpress.org/support/topic/errors-95?replies=3
We should just compare checksums for installed files.

Plugin show false positive for the German specific `liesmich.html`

Plugin is showing false positives for some language packs of bundled themes (but not for all):
- wp-content/languages/themes/twentyfifteen-de_DE.po
- wp-content/languages/themes/twentyfifteen-de_DE.mo
- wp-content/languages/themes/twentyfourteen-de_DE.mo
- wp-content/languages/themes/twentyfourteen-de_DE.po
- wp-content/languages/themes/twentysixteen-de_DE.po

And these harmless `index.php` files
- wp-content/themes/index.php
- wp-content/plugins/index.php

No clue why it is just complaining about these files.

**Comment by swissspidy** [comment] 2016-06-13 11:51
The `liesmich.html` files doesn't exist on every site running `de_DE`, because you could have only installed the language pack, but not the whole localized package. -> exclude these

The blank `index.php` files can be different from the core ones, but not sure if we should exclude those. Those are PHP files after all.

Regarding the translations, I assume that the language packs were updated in the meantime, but the core package uses still the old ones. -> probably safe to exclude language packs from the check as well.

Note: We should display a small note somewhere listing the excluded files.

**Comment by swissspidy** [comment] 2016-06-13 11:52
Oh, and regarding Akismet: Yeah, it's bundled by default and therefore returned by the checksum API. We should only compare files if the file actually exists.

We should check plugin & theme checksums separately from core, see #1.

**Comment by swissspidy** [comment] 2016-07-20 07:15
For comparison, WordPress' own checksum verifier (runs during upgrades) completely skips the `wp-content` directory and any non-existing files.

**Comment by swissspidy** [comment] 2016-07-24 19:34
On the other hand, we should report files inside WordPress directories that do not belong there.

For example, core ticket [#37444](https://core.trac.wordpress.org/ticket/37444) mentions a file `wp-includes/theme-compat/category.php` file with malicious code in it.

**Comment by chesio** [comment] 2017-07-27 16:00
> Regarding the translations, I assume that the language packs were updated in the meantime, but the core package uses still the old ones. -> probably safe to exclude language packs from the check as well.

This seems to still be a problem, I'm getting false positives on the following files:
* wp-content/languages/themes/twentyseventeen-de_DE.po
* wp-content/languages/themes/twentyseventeen-de_DE.mo

**Comment by stklcode** [comment] 2017-07-27 18:13
What about revisiting the previous comment
> WordPress' own checksum verifier (runs during upgrades) completely **skips the wp-content directory** and any non-existing files.

Non-existing are already skipped, so we could add `wp-content` to the default exclusion list. This would exclude Plugins `hello`, `akismet` and the themes shipped by default, which can all be potentially updated at any time. I don't think we need more refined controls on that.

**Comment by stklcode** [comment] 2017-07-27 19:41
Filets like 'liesmich.html' are still potentially detected as false positives as they are apparently not always updated with WP... But a single file can simply be deleted or added to the exclude hook list, instead of adding all languages by default.

**Comment by chesio** [comment] 2017-07-27 21:52
Well, as far as I know, German is the only language that has translation of `readme.html` file shipped with core, so perhaps we could hard-code `liesmich.html` as well... :smile:

**Comment by swissspidy** [comment] 2017-07-27 21:53
I think Japanese translation has lots of custom stuff as well, so I would really double check with translate.wordpress.org.

**Comment by chesio** [comment] 2017-07-27 22:12
I just quickly checked https://api.wordpress.org/core/checksums/1.0/?version=4.8&locale=ja against https://api.wordpress.org/core/checksums/1.0/?version=4.8&locale=en_US and all extra files for Japanese locale are in `wp_content` directory. Same for German locale, except for `liesmich.html` file.

When I'll have more time, I'll code a script to check all available locales, so we know for sure.

**Comment by stklcode** [comment] 2017-07-28 08:04
Interesting, seems we're some kind of special snowflake :smile: But that's good news, so in best case we only have two filenames for exclusion.

The readme files for other locales differ from the US English version, although they're not renamed so the problem stays the same for all translated distributions. Someone should check if there are more special cases (fun work isn't it?), but I suggest to add `readme.html`, `liesmich.html` and probably handfulf other files to the default excluded file.

**Comment by stklcode** [comment] 2017-07-28 08:29
No, German is not the only exception here. Checked out the complete i18n SVN and did a deep search for HTML files in "dist/" ...

Shipped with out supported versions:
* liesmich.html (de_DE)
* lisenssi.html (fi)
* olvasdel.html (hu_HU)
* procitajme.html (hr)
* readme-ja.html (ja, up to 3.9 - we claim 3.8 support...)
* readme.html (most other)

No longer shipped, so we don't have to care about):
* laesmig.html (da_DK, only 1.5)
* readme-en.html (my_MM, only 3.0-3.3)

**Comment by chesio** [comment] 2017-07-28 09:26
Cool finding 👍 Btw. there's also separate `licenc.txt` in Hungarian version... 😄 

Now the question is whether these files still trigger false positives? As @swissspidy noted:
> The liesmich.html files doesn't exist on every site running de_DE, because you could have only installed the language pack, but not the whole localized package. -> exclude these

Any non-existent files are skipped now, so I believe this problem should be solved. Unlike language files (`*.mo` and `*.po`), the readme files should only change when WordPress is updated, so the checksums should always match.

**Comment by stklcode** [comment] 2017-07-28 09:40
Unfortunately it isn't. The problem is not a non-existing file, but an outdated one. Seems that the (localized) readme is not updated as part of the regular process.

I checked on two independent 4.8 setups, both were initially German 3.x bundles. On both a "liesmich.html" is present, but does not match the one shipped with 4.8.

Think the only chance to get out of this is exclude `liesmich.html, olvasdel.html, procitajme.html, readme.html` (maybe the `-ja` for 100% coverage with 3.9). I'd suggest adding it to the default `$ignore_files` array, so a user can un-ignore it in the hook, if he want's to check this file anyway.

**Comment by chesio** [comment] 2017-07-28 10:10
> Seems that the (localized) readme is not updated as part of the regular process.

I run some dummy updates and downgrades with WP-CLI and both readme files have been updated in the process or were re-added if I removed them, so I (falsely) assumed that's what always happens.

> I'd suggest adding it to the default $ignore_files array, so a user can un-ignore it in the hook, if he want's to check this file anyway.

👍

**Comment by stklcode** [comment] 2017-07-28 10:15
I have some test setups installed in the 4.x period on which the files are also up to date. Don't know why and when this happens, maybe if the locale has been switched to English update ran and switched back to German, maybe on multi-locale setups, maybe only on 3.x updates...

**Comment by chesio** [comment] 2017-08-01 11:40
Should be fixed now with #12 merged in.

**Closed by chesio** 2017-08-01 11:40 UTC
Labels: bug
